// Package transport defines the wire protocol shared between the manager
// and worker agents, and the mTLS listeners/clients that speak it.
package transport

import "encoding/json"

// WorkerID stably identifies a worker. It is generated by the worker on
// first enrollment, persisted locally, and used as the client certificate
// common name so the manager can bind a verified cert to a claimed ID.
type WorkerID string

// Report is what a worker POSTs to /report on each interval tick.
type Report struct {
	WorkerID  WorkerID              `json:"worker_id"`
	Hostname  string                `json:"hostname"`
	Timestamp int64                 `json:"timestamp"` // epoch seconds (UTC), set by worker at collection time
	Stats     map[string]StatResult `json:"stats"`     // key = Checker.Name()
}

// StatResult is the outcome of a single check. Value carries a
// checker-specific payload so Report stays stable as individual checkers'
// payload shapes evolve.
type StatResult struct {
	OK    bool            `json:"ok"`
	Error string          `json:"error,omitempty"`
	Value json.RawMessage `json:"value,omitempty"`
}

// ReportAck is the manager's response to a /report POST. It doubles as the
// config-push vehicle: the manager echoes its current desired interval and
// enabled checks so the worker can self-adjust without a separate channel.
type ReportAck struct {
	AcceptedAt      int64    `json:"accepted_at"`
	IntervalSeconds int      `json:"interval_seconds"`
	EnabledChecks   []string `json:"enabled_checks"`
}

// EnrollRequest is POSTed once, over the bootstrap (server-auth-only) TLS
// listener, before the worker has a client cert.
type EnrollRequest struct {
	Token    string `json:"token"`
	Hostname string `json:"hostname"`
	CSRPEM   []byte `json:"csr_pem"` // worker generates its own keypair + CSR; the private key never leaves the worker
}

// EnrollResponse hands the worker everything it needs to start reporting.
type EnrollResponse struct {
	WorkerID        WorkerID `json:"worker_id"`
	ClientCertPEM   []byte   `json:"client_cert_pem"`
	CACertPEM       []byte   `json:"ca_cert_pem"`
	IntervalSeconds int      `json:"interval_seconds"`
	EnabledChecks   []string `json:"enabled_checks"`
	ManagerAddr     string   `json:"manager_addr"` // canonical host:port for the worker to persist and dial for reports
}

// Per-check payload shapes carried in StatResult.Value. Each checker owns
// its own shape; the registry/API layers never need to know them.

type PingResult struct {
	ReachableMs float64 `json:"reachable_ms"`
	PacketLoss  bool    `json:"packet_loss"`
}

type DiskResult struct {
	Path        string  `json:"path"`
	TotalBytes  uint64  `json:"total_bytes"`
	UsedBytes   uint64  `json:"used_bytes"`
	UsedPercent float64 `json:"used_percent"`
}

type MemResult struct {
	TotalBytes  uint64  `json:"total_bytes"`
	UsedBytes   uint64  `json:"used_bytes"`
	UsedPercent float64 `json:"used_percent"`
}

type CPUResult struct {
	UsedPercent float64 `json:"used_percent"`
}

type GitAuthResult struct {
	LoggedIn bool   `json:"logged_in"`
	Account  string `json:"account,omitempty"`
}

// Well-known checker names, used as Report.Stats keys and in
// ManagerConfig/WorkerConfig EnabledChecks lists.
const (
	CheckInternet = "internet"
	CheckDisk     = "disk"
	CheckDRAM     = "dram"
	CheckCPU      = "cpu"
	CheckGitAuth  = "gitauth"
)

// AllChecks is the full set of checks Sitrep knows about, in a stable
// display order used by setup wizards.
var AllChecks = []string{CheckInternet, CheckDisk, CheckDRAM, CheckCPU, CheckGitAuth}
